/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author beto
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.io.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
//import java.io.Serializable;
import javax.swing.Timer;


public class guiFrame extends javax.swing.JFrame implements Serializable {
    
    static JLabel Grid[][] = new JLabel[Board.rows][Board.columns];
    private int currMove = -1;
    private static Player Curr;
    private static Player Play1;
    private static Player Play2;
    public static Timer timer;
    private static int secs, mins = 0;    
    private static String[][] loadedBoard;
    
    /**
     * Creates new form guiFrame
     */
    
    public guiFrame(File load){
     
     Play1 = new Player(WelcomeGUI.Player1Name, "X");
     Play2 = new Player(WelcomeGUI.Player2Name, "O");
     Play2.next = Play1;
     Play1.next = Play2;
     
     int[] Randomize = {1, 2};
     Random getRandom = new Random();
     int select = getRandom.nextInt(Randomize.length);
     if(select == 0){
         Curr = Play1;
     }
     if(select == 1){
         Curr = Play2;
     }
     
     JOptionPane.showMessageDialog(rootPane, Curr.playerName + " First To start.");
     
     initComponents();
     
     try{
        FileInputStream file = new FileInputStream(load);
        ObjectInputStream objectFile = new ObjectInputStream(file);
        loadedBoard = (String [][]) objectFile.readObject();
        
	//Grid = (JLabel[][]) objectFile.readObject();
        System.out.println("Read from file");
        file.close();
	objectFile.close();
        loadGrid(loadedBoard);
        Board.matchBoards(loadedBoard);
        
    }
     catch(Exception ex){
        ex.printStackTrace();
     } 
     for(int j = 0; j < Board.rows; j++) {
      for (int k = 0; k < Board.columns; k++) {
         System.out.print(Grid[j][k].getText());
      }
      System.out.println();
     }
     ///Start Timer. 
     Timer();
     timer.start();
        
    }
    public guiFrame(){
//     Player1.setText("Player 1: " + WelcomeGUI.Player1Name);
//     Player2.setText("Player 1: " + WelcomeGUI.Player2Name);
     
     Play1 = new Player(WelcomeGUI.Player1Name, "X");
     Play2 = new Player(WelcomeGUI.Player2Name, "O");
     Play2.next = Play1;
     Play1.next = Play2;
     
     int[] Randomize = {1, 2};
     Random getRandom = new Random();
     int select = getRandom.nextInt(Randomize.length);
     if(select == 0){
         Curr = Play1;
     }
     if(select == 1){
         Curr = Play2;
     }
     
     JOptionPane.showMessageDialog(rootPane, Curr.playerName + " First To start.");
     
     initComponents();
     fillGrid();
     Timer();
     timer.start();
    }
    
private static int H;
private static int V;
public static void loadGrid(String[][] loaded){
    H = 40;
    V = 20;
    for(int j = 0; j < Board.rows; j++) {
      H = 0;
      for (int k = 0; k < Board.columns; k++) {
          System.out.print(loaded[j][k]);
          Grid[j][k] = new JLabel(loaded[j][k]); 
          Grid[j][k].setFont(new Font("Tohoma", Font.PLAIN,50));
          Grid[j][k].setHorizontalAlignment(SwingConstants.CENTER);
          Grid[j][k].setBounds(H, V, 50, 50);
          jInternalFrame1.getContentPane().add(Grid[j][k]);
          H += 54;
      }
      System.out.println();
      V += 40;
    }
}

public static void fillGrid() {
    H = 40;
    V = 20;
    for(int j = 0; j < Board.rows; j++) {
      H = 0;
      for (int k = 0; k < Board.columns; k++) {
          Board.gameBoard[j][k] = "~";
          Grid[j][k] = new JLabel("~");
          Grid[j][k].setText("~");
          Grid[j][k].setFont(new Font("Tohoma", Font.PLAIN,50));
          Grid[j][k].setHorizontalAlignment(SwingConstants.CENTER);
          Grid[j][k].setBounds(H, V, 50, 50);
          jInternalFrame1.getContentPane().add(Grid[j][k]);
          H += 54;
      } 
      V += 40;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Forfeit = new javax.swing.JButton();
        Restart = new javax.swing.JButton();
        Button8 = new javax.swing.JToggleButton();
        Button7 = new javax.swing.JToggleButton();
        Button6 = new javax.swing.JToggleButton();
        Button5 = new javax.swing.JToggleButton();
        Button4 = new javax.swing.JToggleButton();
        Button3 = new javax.swing.JToggleButton();
        Button1 = new javax.swing.JToggleButton();
        Button2 = new javax.swing.JToggleButton();
        Player2 = new javax.swing.JLabel();
        Player1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        Forfeit.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        Forfeit.setText("Forfeit/Exit");
        Forfeit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForfeitActionPerformed(evt);
            }
        });

        Restart.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        Restart.setText("Restart");
        Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestartActionPerformed(evt);
            }
        });

        Button8.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button8.setText("8");
        Button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button8ActionPerformed(evt);
            }
        });

        Button7.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button7.setText("7");
        Button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button7ActionPerformed(evt);
            }
        });

        Button6.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button6.setText("6");
        Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button6ActionPerformed(evt);
            }
        });

        Button5.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button5.setText("5");
        Button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button5ActionPerformed(evt);
            }
        });

        Button4.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button4.setText("4");
        Button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button4ActionPerformed(evt);
            }
        });

        Button3.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button3.setText("3");
        Button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button3ActionPerformed(evt);
            }
        });

        Button1.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });

        Button2.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Button2.setText("2");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });

        Player2.setText("Player 2: " + Play2.getName() + " " + Play2.getToken());
        Player2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Player1.setText("Player 1: " + Play1.getName() + " " + Play1.getToken());

        jLabel1.setText("Current Player is " + Curr.getName());

        jButton1.setText("Save and Quit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("00:00");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(Forfeit)
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Restart))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Forfeit)
                    .addComponent(Restart)
                    .addComponent(jButton1)))
        );

        jLabel2.getAccessibleContext().setAccessibleName("TimerLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        currMove = 1;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button2ActionPerformed

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        currMove = 0;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button1ActionPerformed

    private void Button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button3ActionPerformed
        currMove = 2;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button3ActionPerformed

    private void Button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button4ActionPerformed
        currMove = 3;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button4ActionPerformed

    private void Button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button5ActionPerformed
        currMove = 4;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button5ActionPerformed

    private void Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button6ActionPerformed
        currMove = 5;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button6ActionPerformed

    private void Button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button7ActionPerformed
        currMove = 6;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button7ActionPerformed

    private void Button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button8ActionPerformed
        currMove = 7;
        Move.getMove(Curr, currMove);
        ConnectFour.check(Curr);
        Curr = Curr.next;
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_Button8ActionPerformed

    private void RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestartActionPerformed
        this.dispose();
        timer.stop();
        run();
        jLabel1.setText(Curr.getName());
    }//GEN-LAST:event_RestartActionPerformed

    private static void Restart(){
        jInternalFrame1.dispose();
        timer.stop();
        WelcomeGUI.run();
    }
    
    private static void totalRestart(){
        jInternalFrame1.dispose();
        //dispose();
        timer.stop();
        run();
    }
    static void Win(int result){
        if(result == 1){
            Restart();
        }
        if(result == 0){
            totalRestart();
        }
    }
    private void ForfeitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForfeitActionPerformed
        JOptionPane.showMessageDialog(rootPane, Curr.playerName + " Wins. Game Over");
        this.dispose();
        timer.stop();
        WelcomeGUI.run();
    }//GEN-LAST:event_ForfeitActionPerformed
    
    /////METHOD TO SAVE AND QUIT GAME
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String filename = JOptionPane.showInputDialog(rootPane, "Enter Name of file to save as");
        timer.stop();        
        
        Board.saveBoard(filename);
        
        this.dispose();
        WelcomeGUI.run();
    }//GEN-LAST:event_jButton1ActionPerformed
        private static DateFormat dateFormat;
        private static Date date;
         //2014/08/06 15:59:48
    public static void Timer(){
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                secs++;
                if(secs%10 == 0){
                    dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    date = new Date();
                    Board.saveBoard(dateFormat.format(date));
                }
               if(secs < 10){
                   jLabel2.setText(mins + ":" + "0" + secs);
               }
               else{
                   jLabel2.setText(mins + ":" + secs);
                   if(secs == 59){
                       mins++;
                       secs=0;
                       jLabel2.setText(mins + ":" + secs);
                   }
               }
              //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        timer.start();
    }
    
    public static void savePlayers(){
        ArrayList<Player> savedPlayers = new ArrayList<Player>();
        savedPlayers.add(Play1);
        savedPlayers.add(Play2);
        savedPlayers.add(Curr);
        
    }
    
    public static void saveTime(){
        ArrayList savedTime = new ArrayList();
        savedTime.add(mins);
        savedTime.add(secs);
    }
    public static void run() {
        new guiFrame().setVisible(true);
    }

    public static void load(File load){
        new guiFrame(load).setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Button1;
    private javax.swing.JToggleButton Button2;
    private javax.swing.JToggleButton Button3;
    private javax.swing.JToggleButton Button4;
    private javax.swing.JToggleButton Button5;
    private javax.swing.JToggleButton Button6;
    private javax.swing.JToggleButton Button7;
    private javax.swing.JToggleButton Button8;
    private javax.swing.JButton Forfeit;
    private javax.swing.JLabel Player1;
    private javax.swing.JLabel Player2;
    private javax.swing.JButton Restart;
    private javax.swing.JButton jButton1;
    private static javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables


}

